openapi: 3.0.0
info:
  title: recipes API
  version: 1.0.0
  description: API specification for the recipes service

paths:
  # BEGIN WORKFLOW AREA route-paths FOR openapi/add-route
  /recipes:
    get:
      $ref: "./routes/recipes/list.yaml#/listRecipes"
    post:
      $ref: "./routes/recipes/create.yaml#/createRecipe"
  /recipes/{id}:
    get:
      $ref: "./routes/recipes/get.yaml#/getRecipe"
    put:
      $ref: "./routes/recipes/update.yaml#/updateRecipe"
    delete:
      $ref: "./routes/recipes/delete.yaml#/deleteRecipe"
  /recipes/{id}/versions:
    get:
      $ref: "./routes/recipes/versions-list.yaml#/listRecipeVersions"
    post:
      $ref: "./routes/recipes/versions-create.yaml#/createRecipeVersion"
  /recipes/{id}/versions/latest:
    put:
      $ref: "./routes/recipes/versions-latest-update.yaml#/updateRecipeVersionLatest"
  # END WORKFLOW AREA

components:
  schemas:
    Error:
      $ref: "./schemas/error.yaml"
    ProductEvent:
      $ref: "./events/index.yaml"
    # BEGIN WORKFLOW AREA schema-components FOR openapi/add-schema

    Recipe:
      $ref: "./schemas/recipe.yaml"
    RecipeVersion:
      $ref: "./schemas/recipe-version.yaml"
    RecipeNote:
      $ref: "./schemas/recipe-note.yaml"
    # END WORKFLOW AREA
