openapi: 3.0.0
info:
  title: recipes API
  version: 1.0.0
  description: API specification for the recipes service

paths:
  /recipes:
    get:
      $ref: "./routes/recipes/list.yaml#/listRecipes"
    post:
      $ref: "./routes/recipes/create.yaml#/createRecipe"
  /recipes/{id}:
    get:
      $ref: "./routes/recipes/get.yaml#/getRecipe"

components:
  schemas:
    Error:
      $ref: "./schemas/error.yaml"
    ProductEvent:
      $ref: "./events/index.yaml"
    # BEGIN WORKFLOW AREA schema-components FOR openapi/add-schema


    Recipe:
      $ref: "./schemas/recipe.yaml"
    RecipeVersion:
      $ref: "./schemas/recipe-version.yaml"
    # END WORKFLOW AREA
