services:
  caddy:
    build:
      context: ../..
      dockerfile: ./hub/dev/Dockerfile.caddy
    ports:
      - 80:80
    volumes:
      - ./caddy-config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - hub-clients

  hub-clients:
    image: sderickson-hub-clients:latest
    build:
      context: ../..
      dockerfile: ./hub/clients/build/Dockerfile
    environment:
      - CLIENT_SUBDOMAINS=,app,auth,account,admin
      - DOMAIN=docker.localhost
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
      - PROTOCOL=${PROTOCOL}
      - SERVICE_SUBDOMAINS=identity,hub
      - TZ=${TZ}
    volumes:
      - ../../hub/clients/:/app/hub/clients/
      - ../../saflib/:/app/saflib/
      - ../../hub/service/sdk/:/app/hub/service/sdk/
    command: npm run dev

  monolith:
    image: sderickson-hub-monolith:latest
    volumes:
      - ../../hub/service/db/data:/app/hub/service/db/data
      - ../../hub/service/cron/data:/app/hub/service/cron/data
      - ../../hub/service/identity/data:/app/hub/service/identity/data
      - ../../recipes/service/db/data:/app/recipes/service/db/data
      - ../../recipes/service/cron/data:/app/recipes/service/cron/data
      - ../../notebook/service/db/data:/app/notebook/service/db/data
      - ../../notebook/service/cron/data:/app/notebook/service/cron/data
      - identity_http_cache:/app/saflib/identity/identity-http/data

    build:
      context: ../..
      dockerfile: hub/service/monolith/Dockerfile

    env_file:
      - ./env.dev

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: "azurite-blob --blobHost 0.0.0.0 --loose"

volumes:
  caddy_data:
  caddy_config:
  identity_http_cache:
