openapi: 3.0.0
info:
  title: notebook API
  version: 1.0.0
  description: API specification for the notebook service

paths:
  # BEGIN WORKFLOW AREA route-paths FOR openapi/add-route
  # END WORKFLOW AREA

components:
  schemas:
    Error:
      $ref: "./schemas/error.yaml"
    ProductEvent:
      $ref: "./events/index.yaml"
    # BEGIN WORKFLOW AREA schema-components FOR openapi/add-schema


    # END WORKFLOW AREA
