services:
  caddy:
    build:
      context: ../..
      dockerfile: ./notebook/dev/Dockerfile.caddy
    ports:
      - 80:80
    volumes:
      - ./caddy-config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - notebook-clients

  notebook-clients:
    image: sderickson-notebook-clients:latest
    build:
      context: ../..
      dockerfile: ./notebook/clients/build/Dockerfile
    environment:
      - CLIENT_SUBDOMAINS=notebook,app.notebook,admin.notebook,account.notebook
      - DOMAIN=docker.localhost
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
      - PROTOCOL=${PROTOCOL}
      - SERVICE_SUBDOMAINS=identity,api.notebook
      - TZ=${TZ}
    volumes:
      - ../../notebook/clients/:/app/notebook/clients/
      - ../../saflib/:/app/saflib/
      - ../../notebook/service/sdk/:/app/notebook/service/sdk/
    command: npm run dev

  monolith:
    image: ghcr.io/sderickson/sderickson-notebook-monolith:latest
    volumes:
      - ../../notebook/service/db/data:/app/notebook/service/db/data
      - ../../notebook/service/cron/data:/app/notebook/service/cron/data
      - ../../hub/service/identity/data:/app/hub/service/identity/data
      - identity_http_cache:/app/saflib/identity/identity-http/data

    build:
      context: ../..
      dockerfile: notebook/service/monolith/Dockerfile

    env_file:
      - ./.env
      - ./env.dev

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: "azurite-blob --blobHost 0.0.0.0 --loose"

volumes:
  caddy_data:
  caddy_config:
  identity_http_cache:
