# common elements between dev and test
services:
  caddy:
    image: caddy:2.9.1
    ports:
      - 80:80
    volumes:
      - ./caddy-config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - NOTEBOOK_DOMAIN=${NOTEBOOK_DOMAIN}
      - PROTOCOL=${PROTOCOL}
      - NOTEBOOK_IDENTITY_SERVICE_HTTP_HOST=${NOTEBOOK_IDENTITY_SERVICE_HTTP_HOST}
      - NOTEBOOK_SERVICE_HTTP_HOST=${NOTEBOOK_SERVICE_HTTP_HOST}
    depends_on:
      - clients

  clients:
    # Named for local dev, but doesn't get published; not needed for prod
    image: sderickson-notebook-clients:latest
    build:
      context: ../..
      dockerfile: ./notebook/clients/build/Dockerfile
    environment:
      - CLIENT_SUBDOMAINS=${NOTEBOOK_CLIENT_SUBDOMAINS}
      - DOMAIN=${NOTEBOOK_DOMAIN}
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
      - PROTOCOL=${PROTOCOL}
      - SERVICE_SUBDOMAINS=${NOTEBOOK_SERVICE_SUBDOMAINS}
      - TZ=${TZ}
    volumes:
      - ../../notebook/clients/:/app/notebook/clients/
      - ../../saflib/:/app/saflib/
      - ../../notebook/service/sdk/:/app/notebook/service/sdk/
    command: npm run dev

  notebook-monolith:
    image: ghcr.io/sderickson/sderickson-notebook-monolith:latest
    volumes:
      - ../../notebook/service/db/data:/app/notebook/service/db/data
      - ../../notebook/service/cron/data:/app/notebook/service/cron/data
      - ../../notebook/service/identity/data:/app/notebook/service/identity/data
      - notebook_identity_http_cache:/app/saflib/identity/identity-http/data

    build:
      context: ../..
      dockerfile: notebook/service/monolith/Dockerfile

    env_file:
      - ./.env
      - ./env.dev

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: "azurite-blob --blobHost 0.0.0.0 --loose"

volumes:
  caddy_data:
  caddy_config:
  notebook_identity_http_cache:
