services:
  caddy:
    build:
      context: ../..
      dockerfile: ./recipes/dev/Dockerfile.caddy
    ports:
      - 80:80
    volumes:
      - ./caddy-config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - recipes-clients

  recipes-clients:
    image: sderickson-recipes-clients:latest
    build:
      context: ../..
      dockerfile: ./recipes/clients/build/Dockerfile
    environment:
      - CLIENT_SUBDOMAINS=recipes,app.recipes,admin.recipes,account.recipes
      - DOMAIN=docker.localhost
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
      - PROTOCOL=${PROTOCOL}
      - SERVICE_SUBDOMAINS=identity,api.recipes
      - TZ=${TZ}
    volumes:
      - ../../recipes/clients/:/app/recipes/clients/
      - ../../saflib/:/app/saflib/
      - ../../recipes/service/sdk/:/app/recipes/service/sdk/
    command: npm run dev

  monolith:
    image: ghcr.io/sderickson/sderickson-recipes-monolith:latest
    volumes:
      - ../../recipes/service/db/data:/app/recipes/service/db/data
      - ../../recipes/service/cron/data:/app/recipes/service/cron/data
      - ../../hub/service/identity/data:/app/hub/service/identity/data
      - identity_http_cache:/app/saflib/identity/identity-http/data

    build:
      context: ../..
      dockerfile: recipes/service/monolith/Dockerfile

    env_file:
      - ./.env
      - ./env.dev

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: "azurite-blob --blobHost 0.0.0.0 --loose"

volumes:
  caddy_data:
  caddy_config:
  identity_http_cache:
